### ISSUE TITLE
Saves files that arent related to saves

### ISSUE THREAD

**Issue by ver151set** [blakekl/rpie-preservatives#7]
This is an issue when using with dreamcast, pc(msdos)

dreamcast it was uploading all the .bin and .raw files which are HUGE

PC it was uploading everything, exe, jpg, pcx, gif, ico, html, pak basically the whole game

For some reason it was also backing up marquees folder in nes roms

I think what I need is to just be able to disable it scanning PC or dreamcast

I tried editing exclusions and it worked on the large dreamcast files and marquees but Im no script guy

      --exclude "*.{${states}${patch_files}xml,png,bin,chx,7z,zip,raw,txt,chd,DS_Store}" \
        --exclude "media/**" \
        --exclude "pc/**" \
        --exclude "marquees/**" \
        --exclude "mame*/**" \
        --exclude "**sd.raw" \
        --exclude "Mupen64plus/**" \
        --exclude "Redream/**" \
        --exclude "User/Cache**" \
        --exclude "User/Config**" \
        --exclude "User/Logs**" \
        --exclude "PSP/SYSTEM/**" \
        --exclude "$exclude"

Thanks for the script!

**Comment by blakekl** [comment]
I can't just have it save .srm because there are other systems that use files outside of .srm (and dreamcast is one of them. The save files for dreamcast are .bin files. Sega Saturn also uses multiples files like .bkr). For the particular issue of dreamcast, I'd suggest converting your dreamcast roms from .cue/.bin format to .chd format instead. The process is quite simple and will fix the issue of .bin files. in addition, .chd will reduce your file size by ~50%, and is a lossless conversion. You can learn more about it here [https://retropie.org.uk/docs/CHD-files/](https://retropie.org.uk/docs/CHD-files/)

As far as your images and everything else, I'm planning to add a custom exclusions field to the config file to allow you to specify your media directory (or any other files really), yourself.  The PC one is a valid bug. I need to add some code to not execute if the system is pc. I'll have to find some free time to get to this. Thanks.

**Comment by ver151set** [comment]
One more thing I noticed, recently with chd files that have multiple discs most are using the .m3u to link multi disc games together and renaming the actual chds to .cd1 .cd2 .cd3 .cd4

This script skips the chds but uploads all the renamed .cd1,cd2 etc that were renamed away from chd as to prevent multiple entries for a game in gamelist

Dreamcast saves arent being uploaded. Im using redream emulator

**Comment by blakekl** [comment]
> One more thing I noticed, recently with chd files that have multiple discs most are using the .m3u to link multi disc games together and renaming the actual chds to .cd1 .cd2 .cd3 .cd4
>
> This script skips the chds but uploads all the renamed .cd1,cd2 etc that were renamed away from chd as to prevent multiple entries for a game in gamelist

For this, don't rename the .chd extension. Instead, put the .cd1 in front of the extension, so something like `ff7.cd1.chd` `ff7.cd2.chd` etc. Be sure to fix the .m3u file contents to match.

> Dreamcast saves arent being uploaded. Im using redream emulator

What do the saves look like for redream? I've only used flycast. From the retroarch documentation, it looks like they're also `.bin` files. And if they are, this should be working already.

[https://docs.libretro.com/library/redream/#directories](https://docs.libretro.com/library/redream/#directories)

**Comment by blakekl** [comment]
I haven't heard back in about a week for additional info. As far as I can tell, this should be working now.
